import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // CSS Variables 集成
        bg: 'var(--color-bg)',
        accent: 'var(--color-accent)',
        primary: 'var(--color-primary)',
        secondary: 'var(--color-secondary)',
        'text-muted': 'var(--color-text-muted)',

        // 保留原有故宫主题色
        'forbidden-red': '#C43232',
        'forbidden-yellow': '#FFB944',
        'forbidden-green': '#2F6F7D',
        'palace-gray': '#8B8B8B',
        'paper-beige': '#F5F1E8',
        'stone-blue': '#4A6FA5',
        'cinnabar-red': '#B94E48',
        'gold-leaf': '#D4AF37',
        'ink-black': '#2C2C2C',
        'jade-green': '#5F9EA0',
        'coral-red': '#FF6F61',
        'royal-purple': '#6B4C9A',

        // Exhibition 页面 - Emerald 绿色系
        'exhibition': {
          primary: '#4a7c59',
          'primary-light': '#8ecf9e',
          'primary-container': '#78a886',
          bg: '#f7f3ed',
          surface: '#faf6f0',
          'on-bg': '#1a2e21',
          'on-surface': '#2e3230',
          outline: '#74796e',
          'outline-variant': '#c4c8bc',
          muted: '#4a4e4a',
        },

        // 开场页 - Material Design 3 颜色系统（暗色主题）
        'on-primary': '#392f16',
        'tertiary-fixed': '#f2e1bc',
        'surface-container-high': '#272b2a',
        'inverse-on-surface': '#2e3130',
        'secondary-fixed': '#e1e3e1',
        'secondary-container': '#474a49',
        'on-surface': '#e1e3e1',
        'surface-container-highest': '#323534',
        'on-tertiary-fixed-variant': '#50462a',
        'on-primary-fixed-variant': '#50462a',
        'on-primary-fixed': '#231b04',
        'tertiary-container': '#f2e1bc',
        'secondary-fixed-dim': '#c5c7c5',
        'on-primary-container': '#6f6345',
        'primary-fixed-dim': '#d5c5a1',
        'surface-bright': '#373a39',
        'primary-fixed': '#f2e1bc',
        'on-error': '#690005',
        'tertiary': '#ffffff',
        'error': '#ffb4ab',
        'on-tertiary': '#392f16',
        'on-secondary-fixed': '#191c1b',
        'inverse-surface': '#e1e3e1',
        'on-surface-variant': '#cdc6b9',
        'on-secondary': '#2e3130',
        'primary-container': '#f2e1bc',
        'background': '#000000',
        'primary': '#ffffff',
        'on-tertiary-container': '#6f6345',
        'on-secondary-fixed-variant': '#444746',
        'secondary': '#c5c7c5',
        'surface-container': '#1d201f',
        'error-container': '#93000a',
        'surface-tint': '#d5c5a1',
        'inverse-primary': '#695d40',
        'outline': '#969084',
        'surface-dim': '#000000',
        'surface-container-low': '#191c1b',
        'on-tertiary-fixed': '#231b04',
        'outline-variant': '#4b463c',
        'surface': '#000000',
        'on-secondary-container': '#b7b9b7',
        'on-error-container': '#ffdad6',
        'tertiary-fixed-dim': '#d5c5a1',
        'surface-container-lowest': '#0c0f0e',
        'on-background': '#e1e3e1',
        'surface-variant': '#323534',

        // 开场页 - 亮色主题
        'light-on-primary': '#f9f7f2',
        'light-tertiary-fixed': '#272b2a',
        'light-surface-container-high': '#e1e3e1',
        'light-inverse-on-surface': '#f9f7f2',
        'light-secondary-fixed': '#2e3130',
        'light-secondary-container': '#c5c7c5',
        'light-on-surface': '#1d201f',
        'light-surface-container-highest': '#cdc6b9',
        'light-on-tertiary-fixed-variant': '#f2e1bc',
        'light-on-primary-fixed-variant': '#f2e1bc',
        'light-on-primary-fixed': '#f9f7f2',
        'light-tertiary-container': '#323534',
        'light-secondary-fixed-dim': '#444746',
        'light-on-primary-container': '#1d201f',
        'light-primary-fixed-dim': '#323534',
        'light-surface-bright': '#ffffff',
        'light-primary-fixed': '#272b2a',
        'light-on-error': '#ffffff',
        'light-tertiary': '#000000',
        'light-error': '#ba1a1a',
        'light-on-tertiary': '#f9f7f2',
        'light-on-secondary-fixed': '#ffffff',
        'light-inverse-surface': '#2e3130',
        'light-on-surface-variant': '#4b463c',
        'light-on-secondary': '#f9f7f2',
        'light-primary-container': '#e1e3e1',
        'light-background': '#F9F7F2',
        'light-primary': '#1d201f',
        'light-on-tertiary-container': '#f2e1bc',
        'light-on-secondary-fixed-variant': '#cdc6b9',
        'light-secondary': '#444746',
        'light-surface-container': '#f1f1f1',
        'light-error-container': '#ffdad6',
        'light-surface-tint': '#272b2a',
        'light-inverse-primary': '#d5c5a1',
        'light-outline': '#7a776e',
        'light-surface-dim': '#e1e3e1',
        'light-surface-container-low': '#f7f9f8',
        'light-on-tertiary-fixed': '#f9f7f2',
        'light-outline-variant': '#cdc6b9',
        'light-surface': '#F9F7F2',
        'light-on-secondary-container': '#191c1b',
        'light-on-error-container': '#410002',
        'light-tertiary-fixed-dim': '#323534',
        'light-surface-container-lowest': '#ffffff',
        'light-on-background': '#1d201f',
        'light-surface-variant': '#e1e3e1',
      },
      fontFamily: {
        songti: ['"Noto Serif SC"', '"Source Han Serif SC"', 'serif'],
        kai: ['"Noto Serif CJK SC"', '"KaiTi"', '"STKaiti"', 'serif'],
        serif: ['"Noto Serif SC"', 'serif'],
        sans: ['Inter', 'sans-serif'],
        // 开场页字体
        headline: ['Newsreader', 'serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Space Grotesk', 'monospace'],
        // 权衡度量体 - 开场页诗句
        quanHeng: ['QuanHeng', 'serif'],
      },
      transitionDuration: {
        fast: 'var(--duration-fast)',
        normal: 'var(--duration-normal)',
        slow: 'var(--duration-slow)',
      },
      backgroundImage: {
        'paper-texture': "url('/textures/paper-texture.jpg')",
        'palace-pattern': "url('/textures/palace-pattern.png')",
      },
      animation: {
        'fade-in': 'fadeIn 1s ease-in-out',
        'slide-up': 'slideUp 0.8s ease-out',
        'slide-down': 'slideDown 0.8s ease-out',
        'scale-in': 'scaleIn 0.6s ease-out',
        float: 'float 3s ease-in-out infinite',
        'pulse-custom': 'pulse 2s ease-in-out infinite',
        'spin-slow': 'spin 3s linear infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(30px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-30px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        pulse: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        spin: {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
      },
    },
  },
  plugins: [],
}
export default config
